# Generated by Django 4.2.11 on 2026-02-04 10:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_license'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='browser_title',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='description',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='font_family',
        ),
        migrations.AddField(
            model_name='organization',
            name='basket_image',
            field=models.ImageField(blank=True, null=True, upload_to='organizations/basket_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png'])]),
        ),
    ]
