# Generated by Django 4.2.11 on 2026-02-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_organization_browser_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key_pem', models.TextField()),
                ('public_key_pem', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Master Key',
                'verbose_name_plural': 'Master Keys',
                'db_table': 'master_keys',
            },
        ),
    ]
